---
title: "analisis_componentes_principales"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r librerias}
library(corrplot)
library(MASS)
library(factoextra)
library(tidyverse)
```

```{r}
datosWB <- read_excel("./Data_Extract_From_World_Development_Indicators .xlsx")

head(datosWB)

#Nombramos las columnas
names(datosWB) <- c("ANIO", "PAIS", "CO2", "ER", "PIB", "GH", "EV", "AE", "GINI", "SS", 
                     "SA", "P", "DE", "EF", "MI", "DEP", "ESC", "HOM")
#Tomamos las columnas de inter?s
datosAux <- datosWB[,3:18]
datosWB<- datosWB[,-c(12)]
#Matriz de correlaci?n
cor(datosAux, use ="na.or.complete")

#Estad?sticas de los datos
summary(datosAux)

#Imputaci?n de datos con la media
datos_media<-datosWB
#CO2
#Notamos que para el 2018, ning?n pa?s tiene registros de C02
for (i in 1:185){
  if(is.na(datos_media[i,"CO2"])){
    p<-as.character(datos_media[i,"PAIS"])
    datos_media[i,"CO2"]<-mean(datos_media$CO2[datos_media$PAIS==p], na.rm=T)
  }
}

#ER
#Solo hay un valor nulo
p<-as.character(datos_media$PAIS[is.na(datos_media$ER)])
datos_media$ER[is.na(datos_media$ER)]<-mean(datos_media$ER[datos_media$PAIS==p], na.rm=T)

#AE
for (i in 1:185){
  if(is.na(datos_media[i,"AE"])){
    p<-as.character(datos_media[i,"PAIS"])
    datos_media[i,"AE"]<-mean(datos_media$AE[datos_media$PAIS==p], na.rm=T)
  }
}

#GINI
for (i in 1:185){
  if(is.na(datos_media[i,"GINI"])){
    p<-as.character(datos_media[i,"PAIS"])
    datos_media[i,"GINI"]<-mean(datos_media$GINI[datos_media$PAIS==p], na.rm=T)
  }
}
#Notar que NZL no tiene calculos del ?ndice de GINI para ning?n a?o

#SS
for (i in 1:185){
  if(is.na(datos_media[i,"SS"])){
    p<-as.character(datos_media[i,"PAIS"])
    datos_media[i,"SS"]<-mean(datos_media$SS[datos_media$PAIS==p], na.rm=T)
  }
}

#SA
for (i in 1:185){
  if(is.na(datos_media[i,"SA"])){
    p<-as.character(datos_media[i,"PAIS"])
    datos_media[i,"SA"]<-mean(datos_media$SA[datos_media$PAIS==p], na.rm=T)
  }
}

#P
# for (i in 1:185){
#   if(is.na(datos_media[i,"P"])){
#     p<-as.character(datos_media[i,"PAIS"])
#     datos_media[i,"P"]<-mean(datos_media$P[datos_media$PAIS==p], na.rm=T)
#   }
# }
# Nueve pa?ses no tiene datos de la tasa de recuento de la pobreza en 
# las l?neas nacionales de pobreza

#DE
#Solo tiene un valor nulo
p<-as.character(datos_media$PAIS[is.na(datos_media$DE)])
datos_media$DE[is.na(datos_media$DE)]<-mean(datos_media$DE[datos_media$PAIS==p], na.rm=T)

#ESC
for (i in 1:185){
  if(is.na(datos_media[i,"ESC"])){
    p<-as.character(datos_media[i,"PAIS"])
    datos_media[i,"ESC"]<-mean(datos_media$ESC[datos_media$PAIS==p], na.rm=T)
  }
}
#Islandia no tiene datos de la media de a?os de escolaridad

#HOM
for (i in 1:185){
  if(is.na(datos_media[i,"HOM"])){
    p<-as.character(datos_media[i,"PAIS"])
    datos_media[i,"HOM"]<-mean(datos_media$HOM[datos_media$PAIS==p], na.rm=T)
  }
}

summary(datos_media)
(comp_prin_media <- analisis_componentes_principales(datos_media))
summary(comp_prin_media, loadings = T)

```
```{r}
#Imputaci?n de datos con el MAXIMO
datos_maximo<-datosWB
#CO2
#Notamos que para el 2018, ning?n pa?s tiene registros de C02
for (i in 1:185){
  if(is.na(datos_maximo[i,"CO2"])){
    p<-as.character(datos_maximo[i,"PAIS"])
    datos_maximo[i,"CO2"]<-max(datos_maximo$CO2[datos_maximo$PAIS==p], na.rm=T)
  }
}

#ER
#Solo hay un valor nulo
p<-as.character(datos_maximo$PAIS[is.na(datos_maximo$ER)])
datos_maximo$ER[is.na(datos_maximo$ER)]<-max(datos_maximo$ER[datos_maximo$PAIS==p], na.rm=T)

#AE
for (i in 1:185){
  if(is.na(datos_maximo[i,"AE"])){
    p<-as.character(datos_maximo[i,"PAIS"])
    datos_maximo[i,"AE"]<-max(datos_maximo$AE[datos_maximo$PAIS==p], na.rm=T)
  }
}

#GINI
for (i in 1:185){
  if(is.na(datos_maximo[i,"GINI"])){
    p<-as.character(datos_maximo[i,"PAIS"])
    datos_maximo[i,"GINI"]<-max(datos_maximo$GINI[datos_maximo$PAIS==p], na.rm=T)
  }
}
#Notar que NZL no tiene calculos del ?ndice de GINI para ning?n a?o

#SS
for (i in 1:185){
  if(is.na(datos_maximo[i,"SS"])){
    p<-as.character(datos_maximo[i,"PAIS"])
    datos_maximo[i,"SS"]<-max(datos_maximo$SS[datos_maximo$PAIS==p], na.rm=T)
  }
}

#SA
for (i in 1:185){
  if(is.na(datos_maximo[i,"SA"])){
    p<-as.character(datos_maximo[i,"PAIS"])
    datos_maximo[i,"SA"]<-max(datos_maximo$SA[datos_maximo$PAIS==p], na.rm=T)
  }
}

#P
# for (i in 1:185){
#   if(is.na(datos_maximo[i,"P"])){
#     p<-as.character(datos_maximo[i,"PAIS"])
#     datos_maximo[i,"P"]<-max(datos_maximo$P[datos_maximo$PAIS==p], na.rm=T)
#   }
# }
# Nueve pa?ses no tiene datos de la tasa de recuento de la pobreza en 
# las l?neas nacionales de pobreza

#DE
#Solo tiene un valor nulo
p<-as.character(datos_maximo$PAIS[is.na(datos_maximo$DE)])
datos_maximo$DE[is.na(datos_maximo$DE)]<-max(datos_maximo$DE[datos_maximo$PAIS==p], na.rm=T)

#ESC
for (i in 1:185){
  if(is.na(datos_maximo[i,"ESC"])){
    p<-as.character(datos_maximo[i,"PAIS"])
    datos_maximo[i,"ESC"]<-max(datos_maximo$ESC[datos_maximo$PAIS==p], na.rm=T)
  }
}
#Islandia no tiene datos de la media de a?os de escolaridad

#HOM
for (i in 1:185){
  if(is.na(datos_maximo[i,"HOM"])){
    p<-as.character(datos_maximo[i,"PAIS"])
    datos_maximo[i,"HOM"]<-max(datos_maximo$HOM[datos_maximo$PAIS==p], na.rm=T)
  }
}

# checking only numeric columns:
datos_maximo <- datos_maximo %>% filter_if(~is.numeric(.), all_vars(!is.infinite(.)))
summary(datos_maximo)
(comp_prin_maximo <- analisis_componentes_principales(datos_maximo))
summary(comp_prin_maximo, loadings = T)
```
```{r}
#Imputaci?n de datos con la mediana
datos_mediana<-datosWB
#CO2
#Notamos que para el 2018, ning?n pa?s tiene registros de C02
for (i in 1:185){
  if(is.na(datos_mediana[i,"CO2"])){
    p<-as.character(datos_mediana[i,"PAIS"])
    datos_mediana[i,"CO2"]<-median(datos_mediana$CO2[datos_mediana$PAIS==p], na.rm=T)
  }
}

#ER
#Solo hay un valor nulo
p<-as.character(datos_mediana$PAIS[is.na(datos_mediana$ER)])
datos_mediana$ER[is.na(datos_mediana$ER)]<-median(datos_mediana$ER[datos_mediana$PAIS==p], na.rm=T)

#AE
for (i in 1:185){
  if(is.na(datos_mediana[i,"AE"])){
    p<-as.character(datos_mediana[i,"PAIS"])
    datos_mediana[i,"AE"]<-median(datos_mediana$AE[datos_mediana$PAIS==p], na.rm=T)
  }
}

#GINI
for (i in 1:185){
  if(is.na(datos_mediana[i,"GINI"])){
    p<-as.character(datos_mediana[i,"PAIS"])
    datos_mediana[i,"GINI"]<-median(datos_mediana$GINI[datos_mediana$PAIS==p], na.rm=T)
  }
}
#Notar que NZL no tiene calculos del ?ndice de GINI para ning?n a?o

#SS
for (i in 1:185){
  if(is.na(datos_mediana[i,"SS"])){
    p<-as.character(datos_mediana[i,"PAIS"])
    datos_mediana[i,"SS"]<-median(datos_mediana$SS[datos_mediana$PAIS==p], na.rm=T)
  }
}

#SA
for (i in 1:185){
  if(is.na(datos_mediana[i,"SA"])){
    p<-as.character(datos_mediana[i,"PAIS"])
    datos_mediana[i,"SA"]<-median(datos_mediana$SA[datos_mediana$PAIS==p], na.rm=T)
  }
}

#P
# for (i in 1:185){
#   if(is.na(datos_mediana[i,"P"])){
#     p<-as.character(datos_mediana[i,"PAIS"])
#     datos_mediana[i,"P"]<-median(datos_mediana$P[datos_mediana$PAIS==p], na.rm=T)
#   }
# }
# Nueve pa?ses no tiene datos de la tasa de recuento de la pobreza en 
# las l?neas nacionales de pobreza

#DE
#Solo tiene un valor nulo
p<-as.character(datos_mediana$PAIS[is.na(datos_mediana$DE)])
datos_mediana$DE[is.na(datos_mediana$DE)]<-median(datos_mediana$DE[datos_mediana$PAIS==p], na.rm=T)

#ESC
for (i in 1:185){
  if(is.na(datos_mediana[i,"ESC"])){
    p<-as.character(datos_mediana[i,"PAIS"])
    datos_mediana[i,"ESC"]<-median(datos_mediana$ESC[datos_mediana$PAIS==p], na.rm=T)
  }
}
#Islandia no tiene datos de la media de a?os de escolaridad

#HOM
for (i in 1:185){
  if(is.na(datos_mediana[i,"HOM"])){
    p<-as.character(datos_mediana[i,"PAIS"])
    datos_mediana[i,"HOM"]<-median(datos_mediana$HOM[datos_mediana$PAIS==p], na.rm=T)
  }
}

summary(datos_mediana)
(comp_prin_mediana <- analisis_componentes_principales(datos_mediana))
summary(comp_prin_mediana, loadings = T)

```
```{r}
#Imputaci?n de datos con el mínimo
datos_minimo<-datosWB
#CO2
#Notamos que para el 2018, ning?n pa?s tiene registros de C02
for (i in 1:185){
  if(is.na(datos_minimo[i,"CO2"])){
    p<-as.character(datos_minimo[i,"PAIS"])
    datos_minimo[i,"CO2"]<-min(datos_minimo$CO2[datos_minimo$PAIS==p], na.rm=T)
  }
}

#ER
#Solo hay un valor nulo
p<-as.character(datos_minimo$PAIS[is.na(datos_minimo$ER)])
datos_minimo$ER[is.na(datos_minimo$ER)]<-min(datos_minimo$ER[datos_minimo$PAIS==p], na.rm=T)

#AE
for (i in 1:185){
  if(is.na(datos_minimo[i,"AE"])){
    p<-as.character(datos_minimo[i,"PAIS"])
    datos_minimo[i,"AE"]<-min(datos_minimo$AE[datos_minimo$PAIS==p], na.rm=T)
  }
}

#GINI
for (i in 1:185){
  if(is.na(datos_minimo[i,"GINI"])){
    p<-as.character(datos_minimo[i,"PAIS"])
    datos_minimo[i,"GINI"]<-min(datos_minimo$GINI[datos_minimo$PAIS==p], na.rm=T)
  }
}
#Notar que NZL no tiene calculos del ?ndice de GINI para ning?n a?o

#SS
for (i in 1:185){
  if(is.na(datos_minimo[i,"SS"])){
    p<-as.character(datos_minimo[i,"PAIS"])
    datos_minimo[i,"SS"]<-min(datos_minimo$SS[datos_minimo$PAIS==p], na.rm=T)
  }
}

#SA
for (i in 1:185){
  if(is.na(datos_minimo[i,"SA"])){
    p<-as.character(datos_minimo[i,"PAIS"])
    datos_minimo[i,"SA"]<-min(datos_minimo$SA[datos_minimo$PAIS==p], na.rm=T)
  }
}

#P
# for (i in 1:185){
#   if(is.na(datos_minimo[i,"P"])){
#     p<-as.character(datos_minimo[i,"PAIS"])
#     datos_minimo[i,"P"]<-min(datos_minimo$P[datos_minimo$PAIS==p], na.rm=T)
#   }
# }
# Nueve pa?ses no tiene datos de la tasa de recuento de la pobreza en 
# las l?neas nacionales de pobreza

#DE
#Solo tiene un valor nulo
p<-as.character(datos_minimo$PAIS[is.na(datos_minimo$DE)])
datos_minimo$DE[is.na(datos_minimo$DE)]<-min(datos_minimo$DE[datos_minimo$PAIS==p], na.rm=T)

#ESC
for (i in 1:185){
  if(is.na(datos_minimo[i,"ESC"])){
    p<-as.character(datos_minimo[i,"PAIS"])
    datos_minimo[i,"ESC"]<-min(datos_minimo$ESC[datos_minimo$PAIS==p], na.rm=T)
  }
}
#Islandia no tiene datos de la media de a?os de escolaridad

#HOM
for (i in 1:185){
  if(is.na(datos_minimo[i,"HOM"])){
    p<-as.character(datos_minimo[i,"PAIS"])
    datos_minimo[i,"HOM"]<-min(datos_minimo$HOM[datos_minimo$PAIS==p], na.rm=T)
  }
}
datos_minimo <- datos_minimo %>% filter_if(~is.numeric(.), all_vars(!is.infinite(.)))
summary(datos_minimo)
(comp_prin_minimo <- analisis_componentes_principales(datos_minimo))
summary(comp_prin_minimo, loadings = T)
```



```{r}

analisis_componentes_principales <- function (datosBase){
  datosBase['ANIO']
  datos_anio<- datosBase[datosBase$ANIO == 2002,]
  datos_anio <- datosBase
  datos <- datos_anio[,c(-1,-2)]
  datos <- datos %>% drop_na()
  pib <- datos$PIB
  datos <- datos[,-3]
  #Nombramos las columnas
  #names(datos) <- c("emisiones_co2", "empleo", "pib", "gasto", "esperanza_vida", "acces_electricidad", "gini", #"serv_sanidad", "serv_agua", "pobreza", "desempleo", "porcent_asalariados", "mort_infan", "porcent_dependientes", #"escuela", "homicidios")
  datos$CO2 <- datos$CO2
  #datos2 <- datos[c(-16,-39, -50),-6]
  summary(datos)
  comp_prin <- princomp(datos, cor = T)
  print(summary(comp_prin, loadings = T))
  print(fviz_screeplot(comp_prin))
  print(fviz_pca_biplot(comp_prin, axes = c(1,2)))
  print(fviz_pca_biplot(comp_prin, axes = c(2,3)))
  print(fviz_pca_biplot(comp_prin, axes = c(3,4)))
  print(fviz_pca_biplot(comp_prin, axes = c(4,5)))
  indice <- as.matrix(datos)%*%comp_prin$loadings[,1]
  print(cor(indice, pib))
  comp_prin
}


```



